### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by Geosearchef** [whirlwind-studios/School1#5]
"There is one branch for each development part (i.e. backend, Android, master for releases and general stuff) within this project. If you have any suggestions regarding this approach, please let me know in the comments, or open an issue."

I'd heavily suggest against using one Repo for all project parts. Seperating into multiple branches is a really bad idea. Keeping everything on one branch forces contributors working on different applications to pull/rebase constantly. Issues/PRs are not seperated. Wiki and documentation are not seperated. The entire repo has to be forked if necessary, ....

Try creating multiple Repos and grouping them using an organization.
e.g.: https://github.com/FAForever

**Comment by Zhyano** [comment]
This is just true, will work on it.

Organization is already created, but... Multi repo approach was unwieldy last time implemented, but was probably just because of me...

Thanks!

**Comment by Zhyano** [comment]
Now created some new repositories, documentation and deletion of old branches etc. is in work
